# Generated by Django 3.1.7 on 2021-02-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210223_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default='', max_length=2048, null=True),
        ),
    ]
